### ISSUE TITLE
Compress-encrypt-decrypt-decompress tests failing on another file

### ISSUE THREAD

**Issue by keepassium** [iharkatkavets/StreamKit#5]
It seems if we use the "PlainText" file instead of the "1MB" one, all the `StreamKitTest.testCompressEncryptDecryptDecompress1MBFileUsing…Stream` tests fail. 
The restored file looks correct, but truncated to chunk size (65536 instead of 74358).

(P.S. No obligations, I just thought you might want to know.)

**Comment by keepassium** [comment]
Found it, just a typo in `decryptAndDecompressFileUsing…` methods:

    while decryptingStream.hasBytesAvailable {
        let readLen = try decompressingStream.read(&tmpBuffer, maxLength: tmpBufferLen)
        try outputFileStream.write(tmpBuffer, length: readLen)
    }

The loop is reading the `decompressingStream`, but monitoring availability of the `decryptingStream`.

**Comment by iharkatkavets** [comment]
Thank you for reporting the issue. I applied the fix and released [v1.0.1](https://github.com/iharkatkavets/StreamKit/releases/tag/1.0.1)
